{
  "extends": ["typescript"],
  "plugins": ["prettier"],
  "parserOptions": {
    "ecmaVersion": 8,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": false,
      "experimentalObjectRestSpread": true
    }
  },
  "env": {
    "node": true,
    "mongo": true
  },
  "rules": {
    "global-require": [
      "error"
    ],
    "semi": [
      "error"
    ],
    "prettier/prettier": [
      "error",
      {
        "semi": true,
        "tabWidth": 4,
        "singleQuote": true,
      }
    ]
  }
}